version: 2.1

executors:
  my-runner:
    machine: true
    resource_class: navi86/default

# Define the jobs we want to run for this project
# jobs:
  # build:
  #   docker:
  #     - image: cimg/<language>:<version TAG>
  #       auth:
  #         username: mydockerhub-user
  #         password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  #   steps:
  #     - checkout
  #     - run: echo "this is the build job"
  # test:
  #   docker:
  #     - image: cimg/<language>:<version TAG>
  #       auth:
  #         username: mydockerhub-user
  #         password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    # steps:
    #   - checkout
    #   - run: echo "this is the test job"

  
workflows:
  my-workflow:
    jobs:
      - my-job

jobs:
  my-job:
    executor: my-runner
    steps:
      - checkout
      - run: echo "Hello from my custom runner!"