name: Build and Test workflow for Spring Boot microservices

on:
  workflow_call:
    inputs:
      dry_run:
        required: false
        type: boolean
        default: false
        description: Build image without pushing it 
      scan_allow_fail:
        required: false
        type: boolean
        default: true
        description: "Mark scan step experimental and not required to pass"
      gcp_project:
        required: false
        type: string
        default: staging
        description: "Mark scan step experimental and not required to pass"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: check_maps
      env:
        lib_suffix: ${{ fromJSON('{"Linux":"so","macOS":"dylib","Windows":"dll"}')[runner.os] }}
        my_project: ${{ fromJSON('{"staging":"staging-number","production":"productions-number"}')[inputs.gcp_project] }}
      run:
        echo $my_project
